### ISSUE TITLE
Wrong texts at Add New User

### ISSUE THREAD

**Issue by mrafsyam** [kemamanwebtech/monash-mec#19]
1. "User gestion" should be User Creation

2. "Log In" button should be "Add new User"

![screenshot from 2016-12-29 16-06-32](https://cloud.githubusercontent.com/assets/6120781/21539560/f76bc1ce-cde2-11e6-940f-d781153219ac.png)

**Comment by iserifith** [comment]
Done . Changes at resources/lang/en/front/form.php .
